### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by bxy666666** [EricKenjiLee/WaveMAP_Paper#5]
hello, Iwant to know the training code, I could not find it, Thanks!

**Comment by EricKenjiLee** [comment]
I'm not 100% sure what you mean but if what you're looking for are the averaged normalized waveforms then you can download it here https://github.com/EricKenjiLee/WaveMAP_Paper/blob/main/data/cleanedWaveforms.mat. Data for other properties like PSTH's and such are also included in that folder. Code that uses this is located here https://github.com/EricKenjiLee/WaveMAP_Paper/blob/main/WaveMAP_Figures_Data.ipynb
